version: "3.9"

services:
  client:
    container_name: scandiweb-test-client
    build: ./client
    networks:
      - frontend
    ports:
      - ${CLIENT_PORT}:80
    restart: always

  server:
    container_name: scandiweb-test-server
    build: ./server
    restart: always
    working_dir: /var/www
    volumes:
      - ./server:/var/www
    networks:
      - frontend
      - backend

  server-nginx:
    container_name: scandiweb-test-server-nginx
    image: nginx:alpine
    restart: always
    ports:
      - ${SERVER_PORT}:80
    volumes:
      - ./server:/var/www
      - ./server/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend

  db:
    container_name: scandiweb-test-db
    image: mysql
    restart: on-failure
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - backend

  phpmyadmin:
    container_name: scandiweb-test-phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
