version: "3.9"

services:
  client:
    container_name: scandiweb-test-client
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - frontend
    ports:
      - 5173:80
    restart: always

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
