-- -- Entity-Attribute-Value (EAV) database model
CREATE DATABASE IF NOT EXISTS SCANDIWEB_TEST;

USE SCANDIWEB_TEST;

CREATE TABLE IF NOT EXISTS PRODUCT(
    sku VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    price FLOAT NOT NULL,
    productType ENUM('DVD', 'Book', 'Furniture') NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY ( sku )
);

CREATE TABLE IF NOT EXISTS PRODUCT_TYPE(
    id BIGINT NOT NULL AUTO_INCREMENT,
    label VARCHAR(255) NOT NULL,
    PRIMARY KEY ( id )
);

INSERT INTO PRODUCT_TYPE(label) VALUES("DVD");
INSERT INTO PRODUCT_TYPE(label) VALUES("Book");
INSERT INTO PRODUCT_TYPE(label) VALUES("Furniture");

CREATE TABLE IF NOT EXISTS PRODUCT_ATTRIBUTE(
    id BIGINT NOT NULL AUTO_INCREMENT,
    label VARCHAR(255) NOT NULL,
    type_id BIGINT NOT NULL,
    PRIMARY KEY ( id ),
    FOREIGN KEY ( type_id ) REFERENCES PRODUCT_TYPE( id ) ON DELETE CASCADE
);

INSERT INTO PRODUCT_ATTRIBUTE(label, type_id) VALUES("size"  , 1);
INSERT INTO PRODUCT_ATTRIBUTE(label, type_id) VALUES("weight", 2);
INSERT INTO PRODUCT_ATTRIBUTE(label, type_id) VALUES("height", 3);
INSERT INTO PRODUCT_ATTRIBUTE(label, type_id) VALUES("width" , 3);
INSERT INTO PRODUCT_ATTRIBUTE(label, type_id) VALUES("length", 3);

CREATE TABLE IF NOT EXISTS PRODUCT_ATTRIBUTE_VALUE(
    id BIGINT NOT NULL AUTO_INCREMENT,
    product_sku VARCHAR(255) NOT NULL,
    attribute_id BIGINT NOT NULL,
    value FLOAT NOT NULL,
    PRIMARY KEY ( id ),
    FOREIGN KEY ( product_sku ) REFERENCES PRODUCT( sku ) ON DELETE CASCADE,
    FOREIGN KEY ( attribute_id ) REFERENCES PRODUCT_ATTRIBUTE( id ) ON DELETE CASCADE
);